dist: zesty
OS: linux
compiler: gcc 
script: make
sudo: disabled
language: C
deploy:
  provider: releases
  api_key:
    secure:  ff3da4d8dc3eb428c112a0212681c6911afefbba
  file: a.out
  skip_cleanup: true
  on:
    tags: true
