dist: zesty
OS: linux
compiler: gcc 
script: make
sudo: disabled
language: C
deploy:
  provider: releases
  api_key:
    secure:  $GT
  file: 
    -task
    -task_reverse.o 
    -reverse_func.o
  on:
    tags: true
